# Generated by Django 4.2.20 on 2025-03-24 15:50

from django.db import migrations
import phonenumbers


def get_pure_phone(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')

    for flat in Flat.objects.iterator():
        raw = flat.owners_phonenumber

        try:
            if raw:
                phone_obj = phonenumbers.parse(raw, 'RU')
                if phonenumbers.is_valid_number(phone_obj):
                    flat.owner_pure_phone = phonenumbers.format_number(
                        phone_obj,
                        phonenumbers.PhoneNumberFormat.E164
                    )
                else:
                    flat.owner_pure_phone = None
            else:
                flat.owner_pure_phone = None

        except phonenumbers.NumberParseException:
            flat.owner_pure_phone = None

        flat.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_flat_owner_pure_phone_alter_complaint_id_and_more'),
    ]

    operations = [
        migrations.RunPython(get_pure_phone)
    ]
