# Generated by Django 4.2.20 on 2025-03-25 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0010_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='pure_phone',
            new_name='pure_phonenumber',
        ),
    ]
