# Generated by Django 4.2.20 on 2025-03-25 06:35

from django.db import migrations


def copy_owners(apps, schema_editor):
    Flat = apps.get_model('property', 'Flat')
    Owner = apps.get_model('property', 'Owner')

    for flat in Flat.objects.all():
        if not flat.owner:
            continue

        Owner.objects.get_or_create(
            name=flat.owner,
            phonenumber=flat.owners_phonenumber,
            pure_phonenumber=flat.owner_pure_phone
        )


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0011_rename_pure_phone_owner_pure_phonenumber'),
    ]

    operations = [
        migrations.RunPython(copy_owners)
    ]
