# Generated by Django 4.2.20 on 2025-03-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0013_auto_20250325_1404'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner_pure_phone',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owners_phonenumber',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
        migrations.AddField(
            model_name='flat',
            name='owner',
            field=models.ManyToManyField(blank=True, related_name='owner', to='property.owner', verbose_name='Владелец'),
        ),
    ]
