# Generated by Django 4.2.20 on 2025-03-25 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_alter_owner_flats_alter_owner_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flat',
            name='owner',
        ),
    ]
