# Generated by Django 4.2.20 on 2025-03-28 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0016_remove_flat_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='owner',
            name='phonenumber',
        ),
    ]
